### ISSUE TITLE
How should I choose a version

### ISSUE THREAD

**Issue by FIREWOODCUT** [ibm-messaging/mq-jms-spring#109]
Hello!
Due to the unique nature of the project, I need to lower the Java compiled version from 8 to 7, which has caused some issues. At first, I thought it was a local environmental issue, but later I created an empty project that could be successfully compiled. As I gradually add dependencies, I try to reduce the versions of various dependencies until 'mq jms spring root starter' and find that it seems that all versions do not support Java 7. What should I do?

**Comment by ibmmqmet** [comment]
Quite apart from this particular package, which has always required a minimum of Java 8
- Spring Boot 2 requires Java 8
- MQ 9.1 onwards requires Java 8

So you might be able to cobble together variants of very old unsupported components, perhaps modifying or  recompiling some parts of it yourself. But otherwise, you'll be out of luck.

**Comment by FIREWOODCUT** [comment]
Okay, thank you for your reply.
