### ISSUE TITLE
MQ Client configuration for SSL with Spring Boot - Provision to provide keystore and trustore

### ISSUE THREAD

**Issue by sathishmurugesan** [ibm-messaging/mq-jms-spring#2]
Please include the following information in your ticket.

Could you please also support configuring SSL using user provided keystore using mqclient to connect to Queue Manager. Currently i dont find place to provide keystore,

**Comment by abedwardsw** [comment]
Use the standard jvm options

-Djavax.net.ssl.keyStore specifies the keystore file.
-Djavax.net.ssl.keyStorePassword specifies the passphrase of the keystore.
-Djavax.net.ssl.trustStore specifies the truststore file to use to validate client certificates.
-Djavax.net.ssl.trustStorePassword specifies the passphrase to access the truststore file

**Comment by ilyako87** [comment]
Hey there.
Unfortunately, this option does not work if I am connecting to multiple Queue Managers with different keystores.
In one case, I have read-only authority, in another case, I have authority to send a message.

**Comment by david0** [comment]
I would also prefer a dedicated configuration option for that, because I'd like to separate the keys/certificate chain used for MQ from the chain used for the rest...

**Comment by thuri** [comment]
We're currently solving this with a custom `com.ibm.mq.spring.boot.MQConnectionFactoryCustomizer` 

```java
@Bean
  public MQConnectionFactoryCustomizer mqConnFactoryCustomizer() {
    return new MQConnectionFactoryCustomizer() {
      @Override
      public void customize(MQConnectionFactory factory) {
        try {
          factory.setObjectProperty(CommonConstants.WMQ_SSL_SOCKET_FACTORY, createSSLSocketFactory());
        } catch (Exception e) {
          throw new IllegalStateException("Adding SSLSocketFactory to WebSphereMQ Factory failed", e);
        }
      }
    };
  }
```

The `createSSLSocketFactory` method reads keystore and trustore from files provided in the configuration and creates a SSLSocketFactory instance using them.

config basically looks like that:

```yaml
ibm.mq:
  jks:
    keystore:
      path: mykestore.jks
      password: 'awesome password'
    truststore:
      path: ${ibm.mq.jks.keystore.path}
      password: ${ibm.mq.jks.keystore.password}
``` 
I'd like to contribute that to the project but i'm not sure wether the CustomizerApproach is ok for that.
It's probably preferable to adjust `com.ibm.mq.spring.boot.MQConnectionFactoryFactory`

so @ibmmqmet What do you prefer?

**Comment by ibmmqmet** [comment]
Putting something in the customizer method is definitely wrong for core code - that method should only be used by user-level configuration like you have done for yourself. Permanent changes would belong in the MQConnectionFactoryFactory. 

The problem I've seen with some of the TLS configuration options is that different JREs might have different JSSE providers, and hence you might need further configuration on which provider class to invoke to get at the real SocketFactory. And then the options on how to set properties like the keystore. That's why I've preferred to delegate/ignore the problem and allow it to be set at the more global level for the Spring application. Usually with `-Djavax.net..` options on startup.

But I'm always open to looking at alternatives if they don't make assumptions about the environment. Perhaps doing it more simply with a configuration method that does things like `System.setProperty("javax.net.ssl.keystore"...)` is preferable.
