### ISSUE TITLE
ConnectionNameList

### ISSUE THREAD

**Issue by dbyrne28** [ibm-messaging/mq-jms-spring#21]
version 2.1.1
jdk openjdk 8

When failing over to a clustered mq(connection named list has more then one server in it), if the pooling property is set to true, the connections are very slow and spinning up more connections is slow.When first connecting, if the first server in the list is the passive server, the pool expands very slowly. If the active server is first, behavior is normal, unless the passive becomes the active, and then the slowness reappears.

**Comment by ibmmqmet** [comment]
This sounds like it's probably due to underlying behaviour of the MQ JMS classes - I believe that connections will always [try the entries in the list from the first](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.dev.doc/q111970_.htm) until it finds one that works. And depending on what the problem is, it may take a while to recognise a connection failure before it tries subsequent entries. 

There's not much that can be done about that in this library, but it might be worth [raising an RFE](https://www.ibm.com/developerworks/rfe) to see if the base interface can be enhanced to do something like automatically reorder the list on retries as it knows which connections have failed. There's no indication back to the caller that a particular conname has succeeded or failed.

This Spring Boot module could conceivably shuffle the connname elements for each connection request but that might have adverse implications such as connecting to a secondary system (not always a failover address) in preference to the primary. Which then leads to needing more configuration controls ...

**Comment by ibmmqmet** [comment]
Nothing to do in this project
