### ISSUE TITLE
How to enable Synched Local Transaction Allowed

### ISSUE THREAD

**Issue by gocoolharsh** [ibm-messaging/mq-jms-spring#61]
Hi I just want to know how we can enable SynchedLocalTransactionAllowed

**Comment by ibmmqmet** [comment]
MQ JMS can participate in full XA transactions under the control of a transaction manager; that's how I would expect operations to be protected. 

There's no real information that I can find on how JMS providers might expose this less-than-reliable transaction management feature. But it appears to be something you can use directly using the Spring Framework APIs, rather than anything implemented in the individual messaging components. There's certainly no reference to it in any of the Sping Boot projects. You're probably better off asking about it in a more general Spring forum.

**Comment by ibmmqmet** [comment]
You may also want to look at the new sample that I just released - in the samples/s2 directory. It demonstrates MQ 1-phase transactions. Suitable where there are no other participants.
