### ISSUE TITLE
Not able to handle the message with CCSID 1200

### ISSUE THREAD

**Issue by thoastast** [ibm-messaging/mq-jms-spring#65]
Please include the following information in your ticket.

- ibmmq-jms-spring version(s) that are affected by this issue: 2.0
- Java version (including vendor and platform).: 11
- A small code sample that demonstrates the issue.

Hi all,

My program is having issue when it is proceeding the message with CCSID 1200.

' with exception '
                       Message : java.lang.Exception
                         Class : class java.lang.Exception
                         Stack : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1923)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveInternal(WMQSyncConsumerShadow.java:230)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.receive(WMQConsumerShadow.java:1465)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.receive(WMQMessageConsumer.java:674)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receiveInboundMessage(JmsMessageConsumerImpl.java:1073)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receive(JmsMessageConsumerImpl.java:691)
                               : com.ibm.mq.jms.MQMessageConsumer.receive(MQMessageConsumer.java:209)
                               : org.springframework.jms.support.destination.JmsDestinationAccessor.receiveFromConsumer(JmsDestinationAccessor.java:132)
                               : org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveMessage(AbstractPollingMessageListenerContainer.java:418)
                               : org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:303)
                               : org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
                               : org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
                               : org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
                               : org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
                               : java.lang.Thread.run(Thread.java:832)
' with MQMD 'version:2(0x2) report:0(0x0) msgType:8(0x8) expiry:-1(0xffffffff) feedback:0(0x0) encoding:546(0x222) codedCharSetId:1200(0x4b0) format:'MQSTR   ' priority:0(0x0) persistence:1(0x1) msgId:414D51204D51535220202020202020209EDC7A5FE01ED22B correlId:000000000000000000000000000000000000000000000000 backoutCount:0(0x0) replyToQ:'                                                ' replyToQMgr:'YYYY                                            ' userIdentifier:'xxxxxxxx   ' accountingToken:16010515000000930F66CD3F53857A46C66A0FF103000000000000000000000B applIdentityData:'                                ' putApplType:11(0xb) putApplName:'mon_VB\VBMQ\MQTSPut_v156.exe' putDate:'20201120' putTime:'10040777' applOriginData:'    ' groupId:000000000000000000000000000000000000000000000000 msgSeqNumber:1(0x1) physicalMsgOffset:0(0x0) msgFlags:0(0x0) originalLength:-1(0xffffffff) '

EXPLANATION:
null

ACTION:
null

The program is working good to the message with CCSID 819 and 1208. Thanks.

Regards,
Thomas

**Comment by ibmmqmet** [comment]
You need to provide a lot more information.
* What do you mean by "program is proceeding"? Do you mean "processing"? 
* Is it your program creating the message or consuming it?
* If consuming, what created it and how?
* Is the message body really in codepage 1200 or are you trying to ask for MQ to convert the message from something else into 1200
* If you are asking for message to be converted to 1200, then how are you doing that
* You say you're using version 2.0 of the boot starter. That'snearly 2 years old and uses a corresponding version of the MQ client.
* What you have put in the description appears to be an entry from an error log rather than a real stack trace. from the execution.
* I'd expect to see a real exception class (eg NPE or JMSException) in a stack dump
* Finally .... this is not likely to be anything to do with this package anyway and the Spring starter doesn't have any real involvement with the actual message content. So if there is a real problem in the MQ JMS classes, you would need to open a support ticket with IBM

**Comment by ibmmqmet** [comment]
No update received.
