### ISSUE TITLE
setup for binding local file

### ISSUE THREAD

**Issue by petrkmoch** [ibm-messaging/mq-jms-spring#72]
I have used local queue manager with JMS administered objects in MQ explorer, provider url like this: file://C:/jndi - there is .binding file, I dont know how to setup application.properties in this situation. Thank you

**Comment by ibmmqmet** [comment]
See https://stackoverflow.com/questions/31493732/spring-boot-reading-spring-jms-jndi-name-property-from-application-properties-f for one example of using Spring's properties for JNDI lookups (rather than any MQ-specific properties) that can feed into the JMSTemplate object.

I am considering adding some explicit JNDI lookups here in the future, but even if I do, they could only be relevant for CFs, not Destinations which are managed outside the scope of this module - you'd still need spring-level properties for queues & topic lookups.
