### ISSUE TITLE
Contribution Agreement - "notify Eclipse Foundation"

### ISSUE THREAD

**Issue by thuri** [ibm-messaging/mq-jms-spring#87]
Hi folks,

I'm preparing a contribution to the project and therefore read the CLA.md file.

Is it correct that it says _You will promptly notify the **Eclipse Foundation**_ in line 31?
The rest of the CLA.md is talking about IBM but that particular line refers to Eclipse Foundation. Ist that correct?

Regards,
Michael

**Comment by ibmmqmet** [comment]
Thanks for pointing that out. The original license for some of these repos was Eclipse-based rather than Apache. And the CLA got seeded from those templates. I think I'll have to talk with lawyers, but I expect I can replace the CLA. The general approach with IBM's repos these days is to use a much simpler file like [this one](https://github.com/hyperledger/fabric/blob/main/docs/source/DCO1.1.txt) instead.
